/*
 * cos.h
 *
 *  Created on: 18.12.2018
 *      Author: Adrian
 */

#ifndef APPLICATION_USER_CIRCULAR_BUFFER_INC_COS_H_
#define APPLICATION_USER_CIRCULAR_BUFFER_INC_COS_H_



#endif /* APPLICATION_USER_CIRCULAR_BUFFER_INC_COS_H_ */
